Algoritmo "Questão 25"

Var
lado1,lado2,lado3:inteiro

Inicio
Escreva("Informe O Valor Do Lador 1:")
Leia(lado1)
Escreva("Informe O Valor Do Lador 2:")
Leia(lado2)
Escreva("Informe O Valor Do Lador 3:")
Leia(lado3)
      se(lado1<lado2+lado3) e (lado2<lado1+lado3) e (lado3<lado1+lado2) entao
      Escreva ("Esta Combinação Forma um Triângulo!")
              senao
                   Escreva("Esta Combinação Não Forma Um Triângulo!")
      FimSe

Fimalgoritmo