Algoritmo "Questão 19"

Var
   nome:caractere
   nota1,nota2,media:real
Inicio
   Escreva ("Qual O Seu Nome?")
   leia(nome)
   Escreva("Informe A Nota Da Prova 1:")
   leia(nota1)
   Escreva("Informe A Nota Da Prova 2:")
   leia(nota2)
   media<-(nota1+nota2)/2
   Se(media>7.0)entao
   Escreva(nome,",Seu Aproveitamento Foi Muito Bom!")
   Senao
   Escreva(nome,",Infelizmente Você Teve Um Aproveitamento Ruim.")
   Fimse
   
   

Fimalgoritmo