Algoritmo "Questão 93"

Var
inicia,pulo,fim:inteiro

Procedimento Contador(I,P,F:Inteiro)
Inicio
Para i<-inicia ate fim passo pulo faca
     Escreval (I)
FimPara
FimProcedimento


Inicio

Escreva("Informe O Número De Partida Da Contagem:")
Leia(inicia)
Escreva("Informe O Número De Salto Da Contagem:")
Leia (pulo)
Escreva("Informe O Número Para Finalização Da Contagem:")
Leia(fim)
LimpaTela
Contador(inicia,pulo,fim)

Fimalgoritmo