Algoritmo "Questão 44"

Var
inicial,final,salto,contador:inteiro

Inicio
Escreva("Informe O Primeiro Valor:")
Leia(inicial)
Escreva("Informe O Ultimo Valor: ")
Leia(final)
Escreva("Informe O Valor De Salto: ")
Leia(salto)
contador<-inicial
limpatela
                 Escreval(contador)
                 Enquanto (contador<=final)faca
                          contador<-contador+salto
                          Escreval(contador)
                 FimEnquanto

Fimalgoritmo